params=['frac_sat_soil_dsl_init','d_max', 'fff','sand_pf',
        'upplim_destruct_metamorph', 
        'z0mr', 'zetamaxstable', 'zsno',
        'medlynintercept','kmax','medlynslope',
        'jmaxb0', 'jmaxb1', 'tpu25ratio',
        'maximum_leaf_wetted_fraction',
        'rhosnir',
        'lmrha',
        'nstem',
        ]

param_colors=['skyblue','skyblue', 'skyblue','skyblue',
        '#F8CBAD', 
              'purple', 'purple', 'purple',
        'forestgreen', 'forestgreen', 'forestgreen',
        'lightseagreen', 'lightseagreen','lightseagreen',
              '#6CD2E9',
              'goldenrod',
              'lightgreen',
        'orange',
              ]


colors=['goldenrod',
        'goldenrod',
        'skyblue',
        'skyblue',
        'skyblue',
        'skyblue',
        '#6CD3E9',
        '#6CD3E9',
        'skyblue',
        'skyblue',
        '#F9CCAD',
        '#F9CCAD',
        'teal',
        'teal',
        'forestgreen',
        'forestgreen',
        'forestgreen',
        'forestgreen',
        'forestgreen',
        'teal',
        'teal',
        'orange',
        'orange',
        'lightseagreen',
        'lightseagreen',
        'teal',
        'forestgreen',
        'teal',
        'skyblue',
        'skyblue',
        'purple',
        'purple',
        'purple',
        'purple',
        'purple',
        'purple']