params=['frac_sat_soil_dsl_init','d_max', 'fff','sand_pf',
        'upplim_destruct_metamorph', 
        'z0mr', 'zetamaxstable', 'zsno',
        'medlynintercept','kmax','medlynslope',
        'jmaxb0', 'jmaxb1', 'tpu25ratio',
        'maximum_leaf_wetted_fraction',
        'rhosnir',
        'lmrha',
        'nstem',
        ]

param_colors=['skyblue','skyblue', 'skyblue','skyblue',
        '#F8CBAD', 
              'purple', 'purple', 'purple',
        'forestgreen', 'forestgreen', 'forestgreen',
        'lightseagreen', 'lightseagreen','lightseagreen',
              '#6CD2E9',
              'goldenrod',
              'lightgreen',
        'orange',
              ]

legend_categories=['Soil hydrology',
        'Snow', 
        'Roughness / boundary layer',
        'Plant water use',
        'Photosynthesis',
                   'Canopy evaporation',
        'Plant radiative properties',
        'Temperature acclimation',
        'Biomass heat storage',
        ]

category_colors=['skyblue',
        '#F8CBAD', 
              'purple', 
        'forestgreen', 
        'lightseagreen', 
               '#6CD2E9',
              'goldenrod',
              'lightgreen',
        'orange',
              ]

"""
params=['frac_sat_soil_dsl_init','d_max', 'fff','sand_pf',
        'upplim_destruct_metamorph', 
        'z0mr', 'zetamaxstable', 'zsno',
        'medlynintercept','kmax','medlynslope',
        'jmaxb0', 'jmaxb1', 'tpu25ratio',
        'maximum_leaf_wetted_fraction',
        'rhosnir',
        'lmrha',
        'nstem',
        ]
param_colors=['skyblue','skyblue', 'skyblue','skyblue',
        '#F8CBAD', 
              'purple', 'purple', 'purple',
        'forestgreen', 'forestgreen', 'forestgreen',
        'lightseagreen', 'lightseagreen','lightseagreen',
              '#6CD2E9',
              'goldenrod',
              'lightgreen',
        'orange',
              ]
"""

colors=['goldenrod',
        'goldenrod',
        'skyblue',
        'skyblue',
        'skyblue',
        'skyblue',
        '#6CD3E9',
        '#6CD3E9',
        'skyblue',
        'skyblue',
        '#F9CCAD',
        '#F9CCAD',
        'teal',
        'teal',
        'forestgreen',
        'forestgreen',
        'forestgreen',
        'forestgreen',
        'forestgreen',
        'teal',
        'teal',
        'orange',
        'orange',
        'lightseagreen',
        'lightseagreen',
        'teal',
        'forestgreen',
        'teal',
        'skyblue',
        'skyblue',
        'purple',
        'purple',
        'purple',
        'purple',
        'purple',
        'purple']

crosswalk_descriptions_short=['rhosnir, min', 'rhosnir, max', 'd_max, min', 'd_max, max',
       'frac_sat_soil_..., min', 'frac_sat_soil_..., max',
       'maximum_leaf_wet..., min',
       'maximum_leaf_wet..., max', 'fff, min', 'fff, max',
       'upplim_destruct_..., min', 'upplim_destruct_..., max',
       'medlynslope, max', 'medlynintercept, min', 'tpu25ratio, min',
       'tpu25ratio, max', 'jmaxb0, max', 'jmaxb1, min', 'jmaxb1, max',
       'kmax, min', 'kmax, max', 'nstem, min', 'nstem, max', 'lmrha, min',
       'lmrha, max', 'medlynslope, min', 'jmaxb0, min',
       'medlynintercept, max', 'sand_pf, min', 'sand_pf, max',
       'z0mr, min', 'z0mr, max', 'zsno, min', 'zsno, max',
       'zetamaxstable, min', 'zetamaxstable, max']

# This is to reorder the ensemble members so parameters are next to each other
int_list=[0,1,2,3,4,5,
          8,9,28,29,6,7,
          25,12,13,27,19,20,
          14,15,26,16,17,18,
          23,24,21,22,10,11,
          32,33,30,31,34,35]